name: PowerfulCookie
version: ${project.version}
main: br.com.devmastersouza.powerfulcookie.PowerfulCookie
authors: [DevMasterSouza]
description: Special powers (effects) on eat cookie
website: https://github.com/DevMasterSouza/PowerfulCookie

commands:
  powerfulcookie:
    description: Powerfulcookie command
    aliases: [pc]